version: "3"

services:
  backend:
    container_name: fastapi-backend
    restart: 'unless-stopped'
    build: .
    ports:
      - "80:80"
    volumes:
      - ./main.db:/src/main.db

networks:
  default:
